---
title: "ggplot"
author: "Brian"
date: "11/3/2020"
output:
  html_document:
    toc: true
    toc_float: true
  pdf_document: 
    latex_engine: xelatex
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# ggplot으로 그래프 그리기

## 데이터

```{r}
library(ggplot2)
midwest
```

## 점 그래프 

```{r}
library(ggplot2)
ggplot(midwest[1:10,], aes(x=county, y=poptotal)) + 
  geom_point()
```

### 색상 수정

```{r}
library(ggplot2)
ggplot(midwest[1:10,], aes(x=county, y=poptotal, color=county)) + 
  geom_point()
```

## 선 그래프 

```{r}
library(ggplot2)
ggplot(midwest, aes(x=area, y=poptotal)) + 
  geom_line()
```

## 막대 그래프

```{r}
library(ggplot2)
ggplot(midwest[1:10,], aes(x=county, y=poptotal)) + 
  geom_bar(stat="identity")
```

### 색상 추가

```{r}
library(ggplot2)
ggplot(midwest[1:10,], aes(x=county, y=poptotal, fill=county)) +
  geom_bar(stat="identity")
```

### 막대 폭 변경

```{r}
library(ggplot2)
ggplot(midwest[1:10,], aes(x=county, y=poptotal, fill=county)) + 
  geom_bar(stat="identity", width=0.2) 
```

### state별로 poptotal 합계

state 그룹별 합계를 구한 후 그래프에 반영하기

```{r message=FALSE}
library(tidyverse)
midwest %>% group_by(state) %>% summarise(all = sum(poptotal)) %>%
  ggplot(aes(x=state,y=all, fill=state)) + 
  geom_bar(stat="identity")
```

## 범례

```{}
```

## 축 수정

### 최대, 최소값 

```{r}
#library(ggplot2)
ggplot(midwest, aes(x=area, y=poptotal)) + 
  geom_point() +
  xlim(c(0, 0.1)) + ylim(c(0, 1000000))
```

### 이름

```{r}
library(ggplot2)
ggplot(midwest[1:10,], aes(x=county, y=poptotal)) + 
  geom_bar(stat="identity") +
  labs(title="Population", x="County", y="Population")

```

### x축 레이블 45도 기울이기

```{r}
library(ggplot2)
ggplot(midwest[1:10,], aes(x=county, y=poptotal, color=county)) + 
  geom_point() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
```

## 회전

```{r}
library(ggplot2)
ggplot(midwest[1:10,], aes(x=county, y=poptotal)) + 
  geom_bar(stat="identity") +
  coord_flip()
```

## 다중 선 그래프 

```{}
```

## 히스토그램 

area의 히스토그램

```{r}
library(ggplot2)
ggplot(midwest, aes(x=area, fill=area)) + 
  geom_histogram()
```

## 그룹별 별도 그래프 

### 점 그래프, state 별로 분리, 세로

```{r}
library(ggplot2)
ggplot(midwest, aes(x=area, y=poptotal, color=area)) + 
  geom_point() +
  facet_grid(state ~ .)
```

### 점 그래프, state 별로 분리, 가로

```{r}
library(ggplot2)
ggplot(midwest, aes(x=area, y=poptotal, color=area)) + 
  geom_point() +
  facet_grid(. ~ state)
```

## Heat map

```{r}
library(ggplot2)
ggplot(midwest,aes(area,popamerindian)) + geom_bin2d(bins=10)
```

## 산포도 

```{r}
library(ggplot2)
ggplot(midwest[1:10,], aes(x=county, y=poptotal)) + 
  geom_point()
```

다중 산포도를 그릴 경우에는 plot함수가 편리

```{r}
library(ggplot2)
plot(midwest[,4:10])
```

## 추세도 

회귀선 추가

```{r}
ggplot(mtcars,aes(x=wt,y=mpg)) + 
  geom_point() + 
  geom_smooth(method = "lm")
```

## 참고자료

* http://r-statistics.co/Complete-Ggplot2-Tutorial-Part1-With-R-Code.html
* http://www.sthda.com/english/wiki/ggplot2-essentials


